-- Seed 25 realistic Greenscape Pro closed-lost leads
-- All synthetic data; numbers are sandbox/test-format only

insert into closed_lost_leads (ghl_contact_id, first_name, last_name, email, phone, city, zip, project_type, est_project_value, last_touchpoint_at, last_touchpoint_summary, reason_lost, notes, status, attempt_count) values
('ghl_001','Alyssa','Whitmore','alyssa.whitmore@example.com','+14805551001','Scottsdale','85254','outdoor kitchen + pergola',62000, now() - interval '11 months', 'Site walk done; scope was outdoor kitchen with pergola cover and seating wall. Loved the design but went cold after we sent the proposal.', 'went cold', 'Husband travels for work; mentioned wanting to do it before next summer.', 'new', 0),
('ghl_002','Marcus','Bell','marcus.bell@example.com','+14805551002','Phoenix','85016','full backyard remodel',95000, now() - interval '14 months','Wanted full backyard: turf, fire pit, water feature, kitchen. Got 3 bids; we were highest. Said quality mattered but timeline was tight.','price','Mentioned a wedding-anniversary deadline he missed; may be ready again.','new',0),
('ghl_003','Priya','Ramachandran','priya.r@example.com','+14805551003','Chandler','85248','pergola + fire pit',31000, now() - interval '8 months','Pergola with built-in fire pit. Liked the renders. Said she would loop husband in and never came back.','went cold','Original interest was clearly genuine; HOA permits were a stated worry.','new',0),
('ghl_004','Daniel','Crowe','daniel.crowe@example.com','+14805551004','Mesa','85207','retaining wall + turf',18500, now() - interval '6 months','New build, sloped backyard. Needed retaining wall and turf install. Went with a competitor who quoted faster.','competitor','Budget was firm; said our quote took too long.','new',0),
('ghl_005','Renata','Oliveira','renata.oliveira@example.com','+14805551005','Tempe','85284','water feature + landscape lighting',24000, now() - interval '4 months','Wanted a custom rock waterfall with low-volt lighting around it. Got the proposal, ghosted after.','went cold','High-end aesthetic preferences; very design-oriented.','new',0),
('ghl_006','Jorge','Mendez','jorge.mendez@example.com','+14805551006','Gilbert','85234','patio + outdoor kitchen',48000, now() - interval '13 months','Travertine patio expansion plus outdoor kitchen with built-in grill, sink, fridge.','price','Explicitly said our pricing was 20% over the next bid.','new',0),
('ghl_007','Hannah','Lerner','hannah.lerner@example.com','+14805551007','Cave Creek','85331','pool deck + pergola',71000, now() - interval '9 months','Pool was already there; needed travertine pool deck and shade pergola.','went cold','Site walk was strong; we were her preferred contractor.','new',0),
('ghl_008','Rashad','Carter','rashad.carter@example.com','+14805551008','Peoria','85383','fire pit + seating wall',14500, now() - interval '5 months','Small project. Fire pit with curved seating wall in flagstone.','price','Said it was a "gift to themselves" and held off until next year.','new',0),
('ghl_009','Wendy','Saito',NULL,'+14805551009','Phoenix','85048','turf + irrigation overhaul',22500, now() - interval '7 months','Wanted to replace dying lawn with premium turf and reset irrigation zones.','went cold','No email on file; phone-only outreach.','new',0),
('ghl_010','Brett','Holloway','brett.holloway@example.com','+14805551010','Scottsdale','85260','outdoor kitchen + pergola + tv wall',88000, now() - interval '15 months','Big build — entertainment-focused yard. Wife was deciding factor and went silent.','went cold','He texted Marcus directly twice; kept saying "next month."','new',0),
('ghl_011','Mei','Tanaka','mei.tanaka@example.com','+14805551011','Tempe','85281','patio + pergola',26000, now() - interval '20 months','Older proposal. May have done the project elsewhere by now.','unknown','Worth one soft re-touch to confirm.','new',0),
('ghl_012','Cole','Ferguson','cole.ferguson@example.com','+14805551012','Mesa','85206','retaining wall + drainage',12500, now() - interval '3 months','Had a flooding problem on slope. Fixed it themselves with a cheap solution.','price','Worth checking back if the cheap solution failed in monsoon season.','new',0),
('ghl_013','Linnea','Vasquez','linnea.vasquez@example.com','+14805551013','Glendale','85308','full backyard remodel',102000, now() - interval '10 months','Full design build. Loved the 3D render. Said her divorce was finalizing.','went cold','Sensitive context; needs careful re-approach.','new',0),
('ghl_014','Omar','Yousef','omar.yousef@example.com','+14805551014','Chandler','85249','pergola + outdoor kitchen',55000, now() - interval '12 months','Said our quote came in two days after a competitor and they had already signed.','competitor','Direct evidence of speed-loss problem.','new',0),
('ghl_015','Elena','Petrova','elena.petrova@example.com','+14805551015','Scottsdale','85255','water feature + landscape redesign',41000, now() - interval '6 months','High-end taste. Ghosted after the proposal.','went cold','Mentioned looking at Italian-style courtyard inspiration.','new',0),
('ghl_016','Drew','Maddox','drew.maddox@example.com','+14805551016','Phoenix','85020','fire pit + grill island',19500, now() - interval '4 months','Said yes verbally; never signed.','went cold','Clear intent; followup may convert immediately.','new',0),
('ghl_017','Yara','Khalil','yara.khalil@example.com','+14805551017','Gilbert','85295','turf + patio',31500, now() - interval '8 months','Wanted turf for kids and a small flagstone patio.','price','Comparing to a chain franchise quote.','new',0),
('ghl_018','Trent','Bishop',NULL,'+14805551018','Mesa','85215','pergola',16500, now() - interval '14 months','Single pergola over existing slab. Got our quote and never replied.','unknown','Phone only; SMS may work if email is unreachable.','new',0),
('ghl_019','Sasha','Greene','sasha.greene@example.com','+14805551019','Cave Creek','85327','outdoor kitchen + fire pit + pergola',73000, now() - interval '16 months','Big scope. Site walk strong. Had some HOA back-and-forth and lost momentum.','went cold','HOA hurdle resolved per LinkedIn (saw they renovated indoor recently).','new',0),
('ghl_020','Beau','Allen','beau.allen@example.com','+14805551020','Peoria','85345','retaining wall + planting',10500, now() - interval '5 months','Smallish project. Said they would defer until tax refund came in.','price','Worth a soft seasonal nudge.','new',0),
('ghl_021','Lina','Hartmann','lina.hartmann@example.com','+14805551021','Scottsdale','85258','full backyard remodel',119000, now() - interval '7 months','Top-tier build. Carlos rendered it. Wife was deciding factor.','went cold','Highest dollar lead in this batch.','new',0),
('ghl_022','Felix','Romero','felix.romero@example.com','+14805551022','Phoenix','85003','patio + irrigation + planting',28500, now() - interval '11 months','Wanted to redo front yard for curb appeal.','went cold','Seasonal timing — spring may be the right re-engagement window.','new',0),
('ghl_023','Imani','Davis','imani.davis@example.com','+14805551023','Tempe','85283','pergola + lighting',21500, now() - interval '6 months','Pergola with custom integrated lighting. Liked the design.','went cold','Solo professional; budget may have shifted.','new',0),
('ghl_024','Adrien','Beauchamp','adrien.beauchamp@example.com','+14805551024','Chandler','85226','outdoor kitchen + tv wall',49000, now() - interval '9 months','Big entertainer. Said his contractor friend would do it cheaper.','price','Friend-contractor deal often falls through; worth a soft follow-up.','new',0),
('ghl_025','Tessa','Brooks','tessa.brooks@example.com','+14805551025','Glendale','85310','fire pit + paver patio',17500, now() - interval '13 months','Small project. Said she would self-perform the patio and just hire us for the fire pit.','price','Self-perform almost certainly stalled — typical pattern.','new',0);
